name: DotW

on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    environment: default
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: node . dotw
